### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ConstanceALOYAU** [BenjaminPellieux/RoboCup_ws#1]
**Votre demande de fonctionnalité est-elle liée à un problème ? Veuillez le décrire.**
Je suis pas d'accord

**Décrivez la solution que vous souhaitez**
Je veux des frites a la cantine 

**Décrivez les alternatives que vous avez envisagées**
Patatose 

**Informations supplémentaires**
Pierre est trop fort

**Comment by BenjaminPellieux** [comment]
Learn Issue
